export const categories = [
  { id: 1, name: "Dresses", slug: "dresses" },
  { id: 2, name: "Tops & Blouses", slug: "tops-blouses" },
  { id: 3, name: "Bottoms", slug: "bottoms" },
  { id: 4, name: "Outerwear", slug: "outerwear" },
  { id: 5, name: "Accessories", slug: "accessories" },
]

export const subcategories = [
  { id: 1, name: "Casual Dresses", categoryId: 1, slug: "casual-dresses" },
  { id: 2, name: "Evening Dresses", categoryId: 1, slug: "evening-dresses" },
  { id: 3, name: "Blouses", categoryId: 2, slug: "blouses" },
  { id: 4, name: "T-Shirts & Tanks", categoryId: 2, slug: "tshirts-tanks" },
  { id: 5, name: "Jeans", categoryId: 3, slug: "jeans" },
  { id: 6, name: "Skirts", categoryId: 3, slug: "skirts" },
  { id: 7, name: "Jackets", categoryId: 4, slug: "jackets" },
  { id: 8, name: "Coats", categoryId: 4, slug: "coats" },
  { id: 9, name: "Handbags", categoryId: 5, slug: "handbags" },
  { id: 10, name: "Jewelry", categoryId: 5, slug: "jewelry" },
]

export const products = [
  {
    id: 1,
    name: "Floral Midi Dress",
    description:
      "Beautiful floral print midi dress perfect for spring and summer occasions. Features a flattering A-line silhouette.",
    price: 89.99,
    originalPrice: 119.99,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop&crop=center",
    categoryId: 1,
    subcategoryId: 1,
    stock: 25,
    rating: 4.8,
    reviews: 156,
    tags: ["floral", "midi", "spring", "feminine"],
    featured: true,
  },
  {
    id: 2,
    name: "Silk Blouse",
    description: "Luxurious silk blouse with elegant draping. Perfect for office wear or special occasions.",
    price: 129.99,
    originalPrice: 159.99,
    image: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=400&h=400&fit=crop&crop=center",
    categoryId: 2,
    subcategoryId: 3,
    stock: 18,
    rating: 4.9,
    reviews: 89,
    tags: ["silk", "elegant", "office", "luxury"],
    featured: true,
  },
  {
    id: 3,
    name: "High-Waisted Jeans",
    description: "Classic high-waisted jeans with a flattering fit. Made from premium denim with stretch for comfort.",
    price: 79.99,
    originalPrice: 99.99,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&h=400&fit=crop&crop=center",
    categoryId: 3,
    subcategoryId: 5,
    stock: 42,
    rating: 4.6,
    reviews: 234,
    tags: ["jeans", "high-waisted", "denim", "classic"],
    featured: false,
  },
  {
    id: 4,
    name: "Evening Gown",
    description: "Stunning evening gown with intricate beadwork. Perfect for formal events and special occasions.",
    price: 299.99,
    originalPrice: 399.99,
    image:
      "https://images.unsplash.com/photo-1567290290527-b553f4d97960?q=80&w=400&h=400&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    categoryId: 1,
    subcategoryId: 2,
    stock: 8,
    rating: 4.9,
    reviews: 67,
    tags: ["evening", "formal", "beaded", "elegant"],
    featured: true,
  },
  {
    id: 5,
    name: "Leather Jacket",
    description: "Edgy leather jacket with a modern cut. Perfect for adding attitude to any outfit.",
    price: 199.99,
    originalPrice: 249.99,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=400&fit=crop&crop=center",
    categoryId: 4,
    subcategoryId: 7,
    stock: 15,
    rating: 4.7,
    reviews: 123,
    tags: ["leather", "jacket", "edgy", "modern"],
    featured: false,
  },
  {
    id: 6,
    name: "Designer Handbag",
    description: "Luxury designer handbag crafted from premium materials. A timeless piece for any wardrobe.",
    price: 349.99,
    originalPrice: 449.99,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=400&fit=crop&crop=center",
    categoryId: 5,
    subcategoryId: 9,
    stock: 12,
    rating: 4.8,
    reviews: 91,
    tags: ["handbag", "designer", "luxury", "premium"],
    featured: false,
  },
  {
    id: 7,
    name: "Cashmere Sweater",
    description: "Ultra-soft cashmere sweater in a classic fit. Perfect for layering or wearing alone.",
    price: 159.99,
    originalPrice: 199.99,
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400&h=400&fit=crop&crop=center",
    categoryId: 2,
    subcategoryId: 3,
    stock: 28,
    rating: 4.9,
    reviews: 178,
    tags: ["cashmere", "sweater", "soft", "luxury"],
    featured: true,
  },
  {
    id: 8,
    name: "Pleated Skirt",
    description: "Elegant pleated skirt that moves beautifully. Perfect for both casual and dressy occasions.",
    price: 69.99,
    originalPrice: 89.99,
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=400&fit=crop&crop=center",
    categoryId: 3,
    subcategoryId: 6,
    stock: 35,
    rating: 4.5,
    reviews: 145,
    tags: ["skirt", "pleated", "elegant", "versatile"],
    featured: false,
  },
  {
    id: 9,
    name: "Statement Necklace",
    description: "Bold statement necklace that elevates any outfit. Features beautiful gemstone details.",
    price: 89.99,
    originalPrice: 119.99,
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop&crop=center",
    categoryId: 5,
    subcategoryId: 10,
    stock: 22,
    rating: 4.6,
    reviews: 87,
    tags: ["necklace", "statement", "jewelry", "gemstone"],
    featured: false,
  },
  {
    id: 10,
    name: "Trench Coat",
    description: "Classic trench coat with timeless appeal. Water-resistant and perfect for transitional weather.",
    price: 249.99,
    originalPrice: 319.99,
    image:
      "https://images.unsplash.com/photo-1633821879282-0c4e91f96232?q=80&w=400&h=400&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    categoryId: 4,
    subcategoryId: 8,
    stock: 16,
    rating: 4.8,
    reviews: 112,
    tags: ["trench", "coat", "classic", "timeless"],
    featured: true,
  },
]

export const users = [
  {
    id: 1,
    name: "Emma Johnson",
    email: "emma@example.com",
    phone: "+1234567890",
    password: "hashedpassword123", // In real app, this would be properly hashed
    createdAt: new Date().toISOString(),
  },
]

export const shippingMethods = [
  { id: 1, name: "Standard Shipping", price: 5.99, estimatedDays: "5-7" },
  { id: 2, name: "Express Shipping", price: 12.99, estimatedDays: "2-3" },
  { id: 3, name: "Overnight Shipping", price: 24.99, estimatedDays: "1" },
]
